---
- name: My first playbook :)
  hosts: "webservers"
  become: true
  become_user: root
  handlers:
    - include: handlers/services.yml
  roles:
    - apache
    - php
    - geerlingguy.memcached
    - geerlingguy.ntp
