---
- name: My first playbook :)
  hosts: "databases"
  become: true
  become_user: root
  vars:
    server_name: localhostNode
    cache_size: 10GB
  tasks:
    - name: "Show message if distribution is Debian"
      debug: msg="Is Debian!"
      when: ansible_os_family == "Debian"

    - name: "Show message if distribution is RedHat"
      debug: msg="Is RedHat!"
      when: ansible_os_family == "RedHat"

    - name: Install Apache
      apt: name=apache2 state=present

    - name: Add configuraction file in Apache conf.d
      copy: src=files/configuration.conf dest=/etc/apache2/configuration.conf

    - name: Create default HTML with SO version
      template: src=templates/index.html dest=/var/www/index_new.html

    - name: restart Apache
      service: name=apache2 state=restarted

    - name: debug
      debug: var=host_name
